//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomRount
    {
        public string Display { get; set; }
        public string Element { get; set; }
        public Nullable<bool> Controller { get; set; }
        public Nullable<bool> Action { get; set; }
    }
}
