//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Job { get; set; }
        public string Favorite { get; set; }
        public string NationlatyId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Nationlaty Nationlaty { get; set; }
    }
}
